In [16]:
import tensorflow as tf
from tensorflow.python.framework import ops
import numpy as np

In [2]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
adder_node = a + b  # + provides a shortcut for tf.add(a, b)
sess = tf.Session()
writer = tf.summary.FileWriter('/data/tensorflow/log', sess.graph)
print(sess.run(adder_node, {a: 3, b:4.5}))
print(sess.run(adder_node, {a: [1,3], b: [2, 4]}))
writer.close()

7.5
[ 3.  7.]


In [3]:
c = tf.greater([1.0,2.0,0.0,3.0,0.0, -.5], 0.0)

In [4]:
sess.run(c)

array([ True,  True, False,  True, False, False], dtype=bool)

In [5]:
x = tf.Variable(.5)
y = tf.cast(tf.greater(x, 0), tf.float32)
tf.gradients([y], [x])

[None]

In [6]:
sess.run(tf.multiply(tf.subtract(tf.cast(c, tf.float32), .5), 2))

array([ 1.,  1., -1.,  1., -1., -1.], dtype=float32)

In [7]:
@ops.RegisterGradient("DubIdent")
def dubIdent(op, grad):
    return [tf.ones(tf.shape(op.inputs[0])), tf.ones(tf.shape(op.inputs[1]))]

@ops.RegisterGradient("Bin_ST")
def bin_ST(op, grad):
    in_vals = op.inputs[0]
    grad_func = tf.cast(tf.less_equal(tf.abs(in_vals), 1), tf.float32)
    grad_out = tf.multiply(grad_func, grad)
    return [grad_out]

### binary sign function with straight through estimator gradient and associated gradient overrides ###
def binarySign(x):
    g = tf.get_default_graph()
    with ops.name_scope("binarySign") as name:       
        with g.gradient_override_map({"Sign": "Bin_ST"}):
            return tf.sign(x)

In [ ]:
### binary sign function with straight through estimator gradient and associated gradient overrides ###
def binaryMultibit(x):
    g = tf.get_default_graph()
    with ops.name_scope("binaryMultibit") as name:       
        with g.gradient_override_map({"Sign": "Bin_ST"}):
            return tf.sign(x)

In [8]:
x = tf.constant([-1,2,-.3, .001, -.2])
y = binarySign(x)
out = tf.gradients([y], [x])

In [9]:
sess.run(out)

[array([ 1.,  0.,  1.,  1.,  1.], dtype=float32)]

In [10]:
g = tf.get_default_graph()
dir(g)
g.get_operations()

[<tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'Placeholder_1' type=Placeholder>,
 <tf.Operation 'add' type=Add>,
 <tf.Operation 'Greater/x' type=Const>,
 <tf.Operation 'Greater/y' type=Const>,
 <tf.Operation 'Greater' type=Greater>,
 <tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Greater_1/y' type=Const>,
 <tf.Operation 'Greater_1' type=Greater>,
 <tf.Operation 'Cast' type=Cast>,
 <tf.Operation 'gradients/Shape' type=Const>,
 <tf.Operation 'gradients/Const' type=Const>,
 <tf.Operation 'gradients/Fill' type=Fill>,
 <tf.Operation 'Cast_1' type=Cast>,
 <tf.Operation 'Sub/y' type=Const>,
 <tf.Operation 'Sub' type=Sub>,
 <tf.Operation 'Mul/y' type=Const>,
 <tf.Operation 'Mul' type=Mul>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'binarySign/Sign' type=Sign>,
 <tf.Operation 'gradients_1/Shape' type=Const>,
 <tf

In [90]:
#x = tf.constant([-1,8,-.3, .001, -.2])
x = tf.constant(10*np.random.rand(10))
#test = tf.nn.l2_normalize(x, dim=0)
round_vals = 3*tf.linspace(-1.0, 1.0, tf.pow(2, 4))
#test = tf.reduce_sum(x)
test_vals = sess.run(round_vals)
test_vals

array([-3.        , -2.5999999 , -2.20000005, -1.79999995, -1.39999986,
       -0.99999994, -0.59999979, -0.19999981,  0.20000017,  0.60000014,
        1.00000012,  1.4000001 ,  1.80000043,  2.20000029,  2.60000038,  3.        ], dtype=float32)

In [91]:
#out = tf.gradients([test], [x])
out = tf.argmax(test)
sess.run(out)

array([[0, 0, 0],
       [0, 0, 0]])

In [177]:
def bit_test(x, num_bits):    
    # normalize globally
    norm = tf.nn.l2_normalize(x, dim = range(len(x.shape)))
    norm = tf.multiply(norm, tf.divide(1.0, tf.reduce_max(norm)))    
    norm = tf.add(norm, 1)
    norm = tf.multiply(norm, tf.pow(2.0, num_bits-1))
    rounded = tf.subtract(tf.cast(tf.ceil(norm + 1e-8), tf.int32), 1)
    round_vals = tf.linspace(-1.0, 1.0, tf.pow(2, num_bits))
    return tf.gather(round_vals, rounded)   

In [179]:
test_op = bit_test(test_vals, 16)
sess.run(test_op)

array([-1.        , -0.86666667, -0.73333335, -0.60000002, -0.46666664,
       -0.33333331, -0.19999999, -0.06666666,  0.06666672,  0.20000005,
        0.33333337,  0.4666667 ,  0.60000002,  0.73333335,  0.86666667,  1.        ], dtype=float32)

In [180]:
test_op = bit_test(test_vals, 2)
sess.run(test_op)

array([-1.        , -1.        , -1.        , -1.        , -0.33333331,
       -0.33333331, -0.33333331, -0.33333331,  0.33333337,  0.33333337,
        0.33333337,  0.33333337,  1.        ,  1.        ,  1.        ,  1.        ], dtype=float32)

In [152]:
test_vals

array([-3.        , -2.5999999 , -2.20000005, -1.79999995, -1.39999986,
       -0.99999994, -0.59999979, -0.19999981,  0.20000017,  0.60000014,
        1.00000012,  1.4000001 ,  1.80000043,  2.20000029,  2.60000038,  3.        ], dtype=float32)